---
:ha: true
:net:
  :svc:
    :if: eth3
    :ip_pri: 172.17.0.11/24
    :ip_sec: 172.17.0.12/24
    :ip_float: 172.17.0.10/24
  :repl:
    :if: bond0
    :ip_pri: 192.168.111.1/30
    :ip_sec: 192.168.111.2/30
  :bonding:
    :if: bond0
    :slave_ifs:
    - eth0
    - eth1
:drbd:
  :pri: /dev/mother/drbd1
  :sec: /dev/mother/drbd1
  :dev: /dev/drbd1
:docker:
  :dns: 172.17.0.10
  :br_ip: 192.168.192.1/24
  :storage:
    :local: /docker-data/local
    :repl: /docker-data/replicated
