---
psql:
  image: 'prozeta/mother-psql'
  env_file: env.sh
  restart: 'unless-stopped'
  net: host
dns:
  image: 'prozeta/mother-dns'
  env_file: env.sh
  restart: 'unless-stopped'
  net: host
dhcp:
  image: 'prozeta/mother-dhcp'
  env_file: env.sh
  restart: 'unless-stopped'
  net: host
tftp:
  image: 'prozeta/mother-tftp'
  env_file: env.sh
  restart: 'unless-stopped'
  net: host
puppetmaster:
  image: 'prozeta/mother-puppetmaster'
  env_file: env.sh
  restart: 'unless-stopped'
  net: host
puppetdb:
  image: 'prozeta/mother-puppetdb'
  env_file: env.sh
  restart: 'unless-stopped'
  net: host
smartproxy:
  image: 'prozeta/mother-smartproxy'
  env_file: env.sh
  restart: 'unless-stopped'
  net: host
foreman:
  image: 'prozeta/mother-foreman'
  env_file: env.sh
  restart: 'unless-stopped'
  net: host
