psql:
  image: prozeta/mother-psql
  env_file: env.sh
  restart: unless-stopped
dns:
  image: prozeta/mother-dns
  env_file: env.sh
  restart: unless-stopped
  ports:
    - 53:53
    - 53:53/udp
dhcp:
  image: prozeta/mother-dhcp
  env_file: env.sh
  restart: unless-stopped
    - 67:67/udp
tftp:
  image: prozeta/mother-tftp
  env_file: env.sh
  restart: unless-stopped
    - 69:69/udp
puppetmaster:
  image: prozeta/mother-puppetmaster
  env_file: env.sh
  ports:
    - 8140:8140
  restart: unless-stopped
puppetdb:
  image: prozeta/mother-puppetdb
  links:
    - psql
    - puppetmaster
  env_file: env.sh
  ports:
  restart: unless-stopped
smartproxy:
  image: prozeta/mother-smartproxy
  links:
    - dhcp
    - dns
    - tftp
    - puppetmaster
  env_file: env.sh
  ports:
    - 8443:8443
  restart: unless-stopped
foreman:
  image: prozeta/mother-foreman
  links:
    - smartproxy
    - psql
    - puppetdb
  env_file: env.sh
  ports:
    - 80:80
    - 443:443
  restart: unless-stopped
