psql:
  build: psql
dns:
  build: dns
dhcp:
  build: dhcp
tftp:
  build: tftp
puppetmaster:
  build: puppetmaster
puppetdb:
  build: puppetdb
smartproxy:
  build: smartproxy
foreman:
  build: foreman
