---
auth:
  db:
    puppet: frxEEI6nmtN9uylievHeVzdMDQJFdkMb
    foreman: lvS2pGSK6AdUm5KyVqGCASvC22kdMsfB
  foreman:
    admin: vthnOnp2NT6Rb1Z7VXaZnNmg8SqoseU8
foreman:
  hostname: foreman.lab.prz
puppet:
  master:
    hostname: puppet.lab.prz
    modules:
    - name: puppetlabs-stdlib
    - name: puppetlabs-concat
    - name: puppetlabs-reboot
    - name: puppetlabs-vcsrepo
    - name: puppetlabs-firewall
    - name: puppetlabs-apt
    - name: puppetlabs-mysql
    - name: puppetlabs-apache
    - name: puppetlabs-inifile
    - name: puppetlabs-lvm
    - name: puppetlabs-stdlib
    - name: puppetlabs-rabbitmq
    - name: puppetlabs-vswitch
    - name: puppetlabs-xinetd
    - name: saz-memcached
    - name: saz-ssh
    - name: elasticsearch-logstashforwarder
    - name: dalen-puppetdbquery
    - name: example42-network
    - name: prozeta-portauthority
    - name: inkblot-ipcalc
    - name: duritong-sysctl
    - name: jhoblitt-ipmi
dhcp:
  subnets:
  - address: 10.248.224.0
    range: [ 10.248.227.1, 10.248.227.220 ]
    netmask: 255.255.252.0
    gateway: 10.248.224.10
    domain: mgmt.lab.prz
    ns:
    - 10.248.224.10
    - 172.17.0.10
    - 172.17.1.0
    pxe: 10.248.224.10
  - address: 10.248.0.0
    netmask: 255.255.248.0
    gateway: 10.248.0.1
    domain: stack-dc1.lab.prz
    ns:
    - 10.248.224.10
    - 172.17.0.10
    - 172.17.1.0
  - address: 10.248.32.0
    netmask: 255.255.248.0
    gateway: 10.248.32.1
    domain: stack-dc2.lab.prz
    ns:
    - 10.248.224.10
    - 172.17.0.10
    - 172.17.1.0
  - address: 10.248.64.0
    netmask: 255.255.248.0
    gateway: 10.248.64.1
    domain: stack-dc3.lab.prz
    ns:
    - 10.248.224.10
    - 172.17.0.10
    - 172.17.1.0
dns:
  mail: 'support.prozeta.eu'
  allow_query:
  - 10.248.0.0/16
  - 172.17.0.0/16
  - 192.168.7.0/24
  - 127.0.0.1/32
  slaves: []
  zones:
  - 'lab.prz'
  - 'mgmt.lab.prz'
  - 'stack-dc1.lab.prz'
  - 'stack-dc2.lab.prz'
  - 'stack-dc3.lab.prz'
  - '248.10.in-addr.arpa'
  slave_zones:
  - masters:
    - 172.17.0.10
    zones:
    - prz
    - cloud.prz
    - mgmt.cloud.prz
    - svc.cloud.prz
    - 17.172.in-addr.arpa
  forwarders:
  - 8.8.8.8
  - 8.8.4.4
